name: merge zeugnis
run-name: ${{ github.actor }} is finalizing CV

on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            lualatex -interaction nonstopmode moderncv/template.tex
            pdfjam "moderncv/template.pdf" "zeugnisse/Abiturzeugnis.pdf" "zeugnisse/EF SET Certificate.pdf" "zeugnisse/Arbeitszeugnis_SVA.pdf" -o template.pdf
